/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AppNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/user-information`; params?: Router.UnknownInputParams; } | { pathname: `/user-information/components/GenderCheckBox`; params?: Router.UnknownInputParams; } | { pathname: `/user-information/components/UserInfoField`; params?: Router.UnknownInputParams; } | { pathname: `/user-information/components/YearPicker`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AppNavigation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/user-information`; params?: Router.UnknownOutputParams; } | { pathname: `/user-information/components/GenderCheckBox`; params?: Router.UnknownOutputParams; } | { pathname: `/user-information/components/UserInfoField`; params?: Router.UnknownOutputParams; } | { pathname: `/user-information/components/YearPicker`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AppNavigation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/user-information${`?${string}` | `#${string}` | ''}` | `/user-information/components/GenderCheckBox${`?${string}` | `#${string}` | ''}` | `/user-information/components/UserInfoField${`?${string}` | `#${string}` | ''}` | `/user-information/components/YearPicker${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AppNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/user-information`; params?: Router.UnknownInputParams; } | { pathname: `/user-information/components/GenderCheckBox`; params?: Router.UnknownInputParams; } | { pathname: `/user-information/components/UserInfoField`; params?: Router.UnknownInputParams; } | { pathname: `/user-information/components/YearPicker`; params?: Router.UnknownInputParams; };
    }
  }
}
